version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
