version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
